version: '3.7'
services:
  service1:
    container_name: app1
    image: kenneth1521412/service1
    build: ./service1
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
  service2:
    container_name: app2
    image: kenneth1521412/service2
    build: ./service2
    ports:
      - target: 5002
        published: 5002
        protocol: tcp
  service3:
    container_name: app3
    image: kenneth1521412/service3
    build: ./service3
    ports:
      - target: 5003
        published: 5003
        protocol: tcp
  service4:
    container_name: app4
    image: kenneth1521412/service4
    build: ./service4
    ports:
      - target: 5004
        published: 5004
        protocol: tcp
  nginx:
    container_name: nginx
    image: nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
   
