- hosts: all
  become: true
  tasks: 
  - name: Install Requirements for Docker
    apt:
      pkg: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      state: latest
      update_cache: true

  - name: Add official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present


  - name: Add apt repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable

  - name: Install Docker
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest
      update_cache: true

  - name: Install Python2
    apt:
      name: python
      state: present
      update_cache: true
 
  - name: Install Python3
    apt:
      name: python3
      state: latest
      update_cache: true

  - name: Install Pip
    apt:
      name: python-pip
      state: present
      update_cache: true

  - name: Install Pip3
    apt:
      name: python3-pip
      state: latest
      update_cache: true

  - name: Install setuptools
    pip:
      name: setuptools
      executable: pip3
      state: latest
     


  - name: Install Docker SDK
    pip:
      name: docker
      state: latest

  - name: Leave Swarm
    docker_swarm:
      state: absent
      force: true
    


- hosts: manager
  become: true
  tasks:
  - name: Leave Swarm
    docker_swarm:
      state: absent
      force: true

  - name: Initialise Docker Swarm
    docker_swarm:
      state: present

  - name: Inspect Swarm 
    docker_swarm:
      state: inspect
    register: token

  - name: Inspect Swarm Nodes
    docker_swarm_info:
      nodes: yes

  - name: Export Variable
    add_host:
      name: "joining"
      value: "{{ token.swarm_facts.JoinTokens.Worker }}"



- hosts: worker
  become: true
  tasks:
  - name: Leave Swarm
    docker_swarm:
      state: absent
      force: true

  - name: Please Leave Swarm
    docker_swarm:
      state: absent
      force: true

  - name: Join Worker 1
    docker_swarm:
      state: join
      advertise_addr: 34.105.191.234  
      join_token: "{{ hostvars['joining']['value'] }}"
      remote_addrs: [ "34.105.244.35:2377" ] 


  - name: Join Worker 2
    docker_swarm:
      state: join
      advertise_addr: 35.197.247.28
      join_token: "{{ hostvars['joining']['value'] }}"
      remote_addrs: [ "34.105.244.35:2377" ]



